# Generated by Django 5.1.7 on 2025-03-09 20:16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestaoCarrinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torneio', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=100)),
                ('ocupante1', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante2', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante3', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante4', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante5', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante6', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante7', models.CharField(blank=True, max_length=100, null=True)),
                ('ocupante8', models.CharField(blank=True, max_length=100, null=True)),
                ('condutor', models.CharField(max_length=100)),
                ('quilometros_saida', models.FloatField()),
                ('quilometros_chegada', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('dia_da_semana', models.CharField(choices=[('segunda-feira', 'Segunda-feira'), ('terça-feira', 'Terça-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('tipo', models.CharField(choices=[('treino', 'Treino'), ('torneio', 'Torneio')], default='Treino', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizadores',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('classe', models.CharField(blank=True, choices=[('MiniBad', 'MiniBad'), ('classe_1', 'Classe 1'), ('classe_2', 'Classe 2'), ('participacao_geral', 'Participação Geral'), ('rendimento', 'Rendimento')], max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='utilizadores_set', related_query_name='utilizadores', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='utilizadores_set', related_query_name='utilizadores', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabril.treinos')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabril.utilizadores')),
            ],
        ),
    ]
